### ISSUE TITLE
Is referencing an object outside the using clause that created it safe?

### ISSUE THREAD

**Issue by anotherlab** [jamesmontemagno/dotnet-maui-configuration#6]
The [code in MauiProgram.cs](https://github.com/jamesmontemagno/dotnet-maui-configuration/blob/93226faa58e0b44d2835b376c82723aca67f1852/MauiApp27/MauiProgram.cs#L21) that loads in the appsettings.json file reads it as a stream.  The stream is opened inside a using statement, but not actually read until after that using statement exits.  Is that safe to use?

```CS
using var stream = a.GetManifestResourceStream("MauiApp27.appsettings.json");

var config = new ConfigurationBuilder()
  .AddJsonStream(stream)
  .Build();
```
Would it be safer to use something like this?

```CS
using (var stream = a.GetManifestResourceStream("MauiApp27.appsettings.json"))
{
  var config = new ConfigurationBuilder()
    .AddJsonStream(stream)
    .Build();
}
```
[Edit]
I'm wrong, the variable should be within scope as [documented](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/using)

**Comment by jamesmontemagno** [comment]
Should be just fine. `using var` handles that stuff.
